customCommands:
  images:
    - name: "Run Neo4j"
      command: "docker run -d --name neo4j -p 7474:7474 -p 7687:7687 -v /home/appez/neo4j/data:/data --env=NEO4J_AUTH=none neo4j:latest"
      description: "Start a Neo4j database in a Docker container"
    - name: "Run Redis"
      command: "docker run -d --name redis -p 6379:6379 --tmpfs /data redis:latest"
      description: "Start a Redis database in a Docker container"

gui:
  returnImmediately: true
